/*******************************

王心凌5.17票信息

*******************************

[rewrite_local]

^https?:\/\/yanchu\.maoyan\.com\/myshow\/ajax\/v2\/show\/1882472\/tickets$ url script-response-body https://raw.githubusercontent.com/ciaooo55/CLASH/main/QuantumultX/maoyan/piao.js
^https?:\/\/wx\.maoyan\.com\/maoyansh\/myshow\/ajax\/v2\/show\/1892583\/tickets$ url script-response-body https://raw.githubusercontent.com/ciaooo55/CLASH/main/QuantumultX/maoyan/piao.js

[mitm]
hostname = yanchu.maoyan.com, wx.maoyan.com

*******************************/

var body = $response.body;
body = JSON.stringify({
    code: 200,
    msg: "",
    data: [
        {
            showTicketClassId: 21134483,
            ticketClassId: 21134483,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 1618,
            sellPrice: 1618,
            setNumber: 1,
            set: false,
            description: "内场",
            ticketName: "内场",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        },
        {
            showTicketClassId: 21134484,
            ticketClassId: 21134484,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 1318,
            sellPrice: 1318,
            setNumber: 1,
            set: false,
            description: "内场",
            ticketName: "内场",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        },
        {
            showTicketClassId: 21134485,
            ticketClassId: 21134485,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 1118,
            sellPrice: 1118,
            setNumber: 1,
            set: false,
            description: "内场",
            ticketName: "内场",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        },
        {
            showTicketClassId: 21134486,
            ticketClassId: 21134486,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 818,
            sellPrice: 818,
            setNumber: 1,
            set: false,
            description: "看台",
            ticketName: "看台",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        },
        {
            showTicketClassId: 21134487,
            ticketClassId: 21134487,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 618,
            sellPrice: 618,
            setNumber: 1,
            set: false,
            description: "看台",
            ticketName: "看台",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        },
        {
            showTicketClassId: 21134488,
            ticketClassId: 21134488,
            performanceId: 323101,
            showId: 1882472,
            ticketPrice: 318,
            sellPrice: 318,
            setNumber: 1,
            set: false,
            description: "看台",
            ticketName: "看台",
            editStatus: 1,
            stockable: false,
            rgb: "",
            rectIds: null,
            ticketLevel: "",
            setDiscountInfoList: null,
            baseTicketID: 0,
            salesPlanVO: null,
            memberInfoVO: null,
            discountSum: 0,
            onSaleTime: null,
            specificTimeSale: 0,
            maxBuyLimit: 20,
            minBuyLimit: 0,
            userBuyLimit: 0,
            remainingStock: 20,
            tpId: 0,
            salesPlanId: 0,
            supplierPrice: null,
            showStatus: 0,
            discount: null,
            sortWeight: 0,
            activityRuleList: null
        }
    ],
    paging: null,
    attrMaps: {
        serverTime: 1715677677350
    },
    success: true
});

$done({body});
